[package]
name = "graphui-rs"
version = "0.0.1"
authors = ["Tom A. Wagner <tom.a.wagner@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pipewire = { git = "https://gitlab.freedesktop.org/gdesmott/pipewire-rs", branch = "proxies"}
gtk = { git = "https://github.com/gtk-rs/gtk4-rs/", package = "gtk4" }
