[package]
name = "graphui"
version = "0.1.0"
authors = ["Tom A. Wagner <tom.a.wagner@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libspa = { git = "https://gitlab.freedesktop.org/pipewire/pipewire-rs" }
pipewire = { git = "https://gitlab.freedesktop.org/pipewire/pipewire-rs" }
gtk = { git = "https://github.com/gtk-rs/gtk4-rs/", package = "gtk4" }

log = "0.4.11"
env_logger = "0.8.2"
